# Instructions

1. Click an item from $\color{#B24745FF}{\text{Disorder}}$ drop-down menu to navigate to the disease type of your interest.
2. Click an item from $\color{#B24745FF}{\text{State}}$ drop-down menu to switch between database of each state.
3. Click on the $\color{#B24745FF}{\text{Browse...}}$ button to choose a input file from local device. 
4. Choose the $\color{#B24745FF}{\text{delimiter}}$ of your input file and click "RUSP_RF".
5. Click the $\color{#B24745FF}{\text{Run RUSP_RF}}$ button to submit the input file. Once the calculation is done, the result figure and table will show on the right panel. 
6. A $\color{#B24745FF}{\text{recommended sensitivity cutoff}}$ is used by default for deciding true/false postives in the first calculation. The sensitivity cutoff is also $\color{#B24745FF}{\text{customizable}}$ with the slider bar on the left-side panel.
7. You could $\color{#B24745FF}{\text{specify/underline a sample or multiple samples}}$ on the figure by clicking the corresponding row on the table. Click the row once again to cancel the specification. 
8. Type in a keyword in the $\color{#B24745FF}{\text{search}}$ field to search for a certain information. 
9. Click on the $\color{#B24745FF}{\text{Download figure/table}}$ button to download the results to your local devices to view them offline.
10. While navigating to a new disease type, a popup dialog with the text "If you choose to continue, the current results will be cleared. Please download the results beforehand if you prefer to keep a record." will appear. If the user choose to $\color{#B24745FF}{\text{continue}}$, the application will switch to the corresponding model.

The application won't keep record of any of your data or the results. Your information won't be tracked when you visit this website.

We welcome comments, suggestions and questions. Please feel free to send emails to us by clicking '[Report issues to the developers](gang.peng@yale.edu)' from the bottom of the left panel. We will try our best to reply back to you in a timely manner.
